version: '2.4'

services:
  db:
    build: ./db
    container_name: db
    environment:
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: CMD pg_isready -q || echo 1
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - 5432:5432

  java:
    build: ./java
    container_name: serv
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: volume
        source: m2_home
        target: /root/.m2
    ports:
      - 8080:8080

volumes:
  m2_home:
    name: m2_home